# Generated by Django 5.1.4 on 2025-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_back_card_type_card_back_color_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
