# Generated by Django 5.1.4 on 2025-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_importtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='multiverse_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
